# -*- coding: utf-8 -*-
"""оу ноу и не оу ноу.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1glN3ZhxOofKEsWV9IM5C59bL4Z4TaGNf
"""

a=int(input())
if a==1:
    print("Январь")
elif a==2:
    print("февраль")
elif a== 3:
    print("Март")
elif   a == 4:
    print("Апрель")
elif  a == 5:
    print("май")
elif  a == 6:
    print("Июнь")
elif  a == 7:
    print("Июль")
elif a == 8:
    print("август")
elif a==9:
    print("сентября")
elif a==10:
    print("Октябрь")
elif a==11:
    print("ноябрь")
elif a==12:
    print("Декабрь")
else:
    print("номер месяцв введен не корректно")

a=int(input())
if a % 2 ==0:
  print("число четное")
else:
  print("оу ноу оно нечетное")

a=int(input())
if a>40:
  print("стонкс")
else:
  print(" оу ноу нот стонкс")

a=int(input())
if (a % 4 == 0 and a % 100 !=0) or a % 400 ==0:
    print("трушно")
else:
    print("оу ноу нетрушно")

a=int(input())
b=0
for v in range (2, a//2 + 1):
    if a % v ==0:
      b+=1
if b==0:
      print("трушно")
else:
      print("ты сам знаешь,что нетрушно")

x= float(input())
y= float(input())
if x/y == 3.6:
  x ,y = y ,x
  print("поменялись")
elif abs((-138/2) ** 1.3) <= y and y<= abc (((-69 / 28)** 5.1) * 4):
  x , y = y, x
  print(" поменялись")
else:
  print("оу ноу не поменялись")

a=[]
k1, k2, k3 = 0, 0, 0
for x in range(5):
  a.append(int(input()))
  if x % 2 ==0:
    k1 += 1
  if x % 2!=0:
    k2 == 1
  if -256 <= x <= 1024:
    k3 += 1
for i in range(len(a)-1):
  for j in range(i+1, len (a)):
    if a[j] == a[i]:
      print(" оу ноу они не уникальны")
print ('уникалки')
print (a, k1, k2, k3)

a= int(input())
b= int(input())
c= int(input())
d = ((a ** 2 + b ** 3)/ (c + 3)) / 4
if d > 14:
  if a % 2 == 0:
    print('четкое')
  if a % 2 !=0:
    print("нечеткое")
  if b % 2 == 0:
    print ("четкое")
  if b % 2 != 0:
    print ("нечеткое")
  if с % 2 == 0:
    print ("четкое")
  if с % 2 != 0:
    print ("notчеткое")
else:
  print("оу ноу нет решения3")

